name: Test on MacOS

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        rust-toolchain: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2
      - name: Use Rust ${{ matrix.rust-toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: x86_64-apple-darwin
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install workspace
        run: npm install
      - name: run tests
        run: npm test
