name: Test on Windows

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
        rust-toolchain: [ stable, beta, nightly ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Rust ${{ matrix.rust-toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: x86_64-pc-windows-msvc
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use npm v6
        if: ${{ matrix.node-version == '16.x' }}
        run: npm install -g npm@6
      - name: Install libclang
        uses: KyleMayes/install-llvm-action@01144dc97b1e2693196c3056414a44f15180648b
        with:
          version: "10"
          directory: ${{ runner.temp }}/llvm
      - run: npm config set msvs_version 2019
      - name: npm install workspace
        run: npm install
      - name: run tests
        run: npm test
        env:
          LIBCLANG_PATH: ${{ runner.temp }}/llvm/bin
